const HOST = "http://0.0.0.0:8091/";
const PREFIX_PATH = "api/v1000"

const REQUEST_STATE = {
    SUCCESS: "_SUCCESS",
    FAILURE: "_FAILURE",
    REQUESTING: "_REQUESTING"
}

const REQUEST_DATA = 'REQUEST_DATA';

const RECEIVE_DATA = 'RECEIVE_DATA';

export {
    HOST, 
    PREFIX_PATH, 
    REQUEST_STATE,
    REQUEST_DATA,
    RECEIVE_DATA
};